DROP TABLE IF EXISTS STATS CASCADE;

CREATE TABLE IF NOT EXISTS STATS
(
    ID      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    APP     VARCHAR(255) NOT NULL,
    URI     VARCHAR(255) NOT NULL,
    IP      VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP WITHOUT TIME ZONE
    );