version: '3.1'
services:
  stat-server:
    build: ./stat-service/server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=statdb
      - SPRING_DATASOURCE_PASSWORD=statdb

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stat-db
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=statdb
      - POSTGRES_PASSWORD=statdb

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewmdb
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=statdb
      - SPRING_DATASOURCE_PASSWORD=statdb
      - SERVICES_STATSSERVICE_URI=http://stat-server:9090

  ewmdb:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewmdb
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=statdb
      - POSTGRES_PASSWORD=statdb
